spring:
  application:
    name: m42hub-api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enable: true

m42hub:
  security:
    secret: ${SECRET}
    cookie-secure: false

cors:
  allowed-origins:
    http://localhost:4200
    https://www.m42hub.com
